on:
  push:
    branches:
      - '**' 

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mars-rovers/python-mars-rovers
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: poetry install --no-interaction

      - run: poetry run pytest