on:
  push:
    branches:
      - '**' 

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./calculator/fraction-lib
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@rlratcliffe'

      - run: make build

      - run: make test

      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build app
        working-directory: ./calculator/calculator-front-end
        run: |
          ls
          npx expo export --platform web

      - name: Deploy with rsync
        working-directory: ./calculator/calculator-front-end
        env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          rsync -avz ./dist/ $SSH_USER@$SSH_HOST:/var/www/html